# Generated by Django 2.2.3 on 2019-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='grouptype',
            field=models.CharField(blank=True, choices=[('BVC', 'Bitcoin value chart'), ('CI', 'Companie info'), ('DJC', 'Dow jones companies')], max_length=3),
        ),
    ]
