# Generated by Django 2.2.3 on 2019-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190728_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grouptype',
            field=models.CharField(blank=True, choices=[('Chart', (('BVC', 'Bitcoin Value Chart'), ('2WBA', 'Weibo Corp'), ('ADBE', 'Adobe Systems Inc'), ('ADSK', 'Autodesk Inc'), ('APPL', 'Apple Inc'), ('BB', 'BlackBerry Ltd'), ('DBTK', 'Double-Take Software, Inc'), ('DELL', 'Dell Technologies Inc'), ('GDDY', 'GoDaddy Inc'), ('MFE', 'McAfee, Inc'), ('NVDA', 'NVIDIA Corp'), ('THQIQ', 'THQ INC'), ('TMUS', 'T-Mobile US Inc'), ('TWTR', 'Twitter Inc'), ('VOD', 'Vodafone Group PLC'))), ('Information', (('INF2WBA', 'Weibo Corp'), ('INFADBE', 'Adobe Systems Inc'), ('INFADSK', 'Autodesk Inc'), ('INFAPPL', 'Apple Inc'), ('INFBB', 'BlackBerry Ltd'), ('INFDBTK', 'Double-Take Software, Inc'), ('INFDELL', 'Dell Technologies Inc'), ('INFGDDY', 'GoDaddy Inc'), ('INFMFE', 'McAfee, Inc'), ('INFNVDA', 'NVIDIA Corp'), ('INFTHQIQ', 'THQ INC'), ('INFTMUS', 'T-Mobile US Inc'), ('INFTWTR', 'Twitter Inc'), ('INFVOD', 'Vodafone Group PLC'))), ('DJC', 'Dow Jones Companies')], max_length=3),
        ),
    ]
