# Generated by Django 2.2.3 on 2019-07-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20190728_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grouptype',
            field=models.CharField(blank=True, choices=[('Chart', (('CHTBVC', 'Bitcoin Value Chart'), ('CHTADBE', 'Adobe Systems Inc'), ('CHTADSK', 'Autodesk Inc'), ('CHTAAPL', 'Apple Inc'), ('CHTBB', 'BlackBerry Ltd'), ('CHTDBTK', 'Double-Take Software, Inc'), ('CHTDELL', 'Dell Technologies Inc'), ('CHTGDDY', 'GoDaddy Inc'), ('CHTMFE', 'McAfee, Inc'), ('CHTNVDA', 'NVIDIA Corp'), ('CHTTHQIQ', 'THQ INC'), ('CHTTMUS', 'T-Mobile US Inc'), ('CHTVOD', 'Vodafone Group PLC'))), ('Information', (('INFADBE', 'Adobe Systems Inc'), ('INFADSK', 'Autodesk Inc'), ('INFAAPL', 'Apple Inc'), ('INFBB', 'BlackBerry Ltd'), ('INFDBTK', 'Double-Take Software, Inc'), ('INFDELL', 'Dell Technologies Inc'), ('INFGDDY', 'GoDaddy Inc'), ('INFMFE', 'McAfee, Inc'), ('INFNVDA', 'NVIDIA Corp'), ('INFTHQIQ', 'THQ INC'), ('INFTMUS', 'T-Mobile US Inc'), ('INFVOD', 'Vodafone Group PLC'))), ('DJC', 'Dow Jones Companies')], max_length=8),
        ),
    ]
