# Generated by Django 2.2.3 on 2019-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20190728_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grouptype',
            field=models.CharField(blank=True, choices=[('Company Chart', (('CHTMMM', '3M'), ('CHTAAPL', 'Apple'), ('CHTAXP', 'American Express'), ('CHTBA', 'Boeing'), ('CHTCAT', 'Caterpillar'), ('CHTCSCO', 'Cisco'), ('CHTKO', 'Coca-Cola'), ('CHTGS', 'Goldman Sachs'), ('CHTIBM', 'IBM'), ('CHTINTC', 'Intel'), ('CHTNKE', 'Nike'), ('CHTPFE', 'Pfizer'), ('CHTVZ', 'Verizon'), ('CHTV', 'Visa'), ('CHTWTM', 'Wallmart'))), ('Information', (('INFMMM', '3M'), ('INFAAPL', 'Apple'), ('INFAXP', 'American Express'), ('INFBA', 'Boeing'), ('INFCAT', 'Caterpillar'), ('INFCSCO', 'Cisco'), ('INFKO', 'Coca-Cola'), ('INFGS', 'Goldman Sachs'), ('INFIBM', 'IBM'), ('INFINTC', 'Intel'), ('INFNKE', 'Nike'), ('INFPFE', 'Pfizer'), ('INFVZ', 'Verizon'), ('INFV', 'Visa'), ('INFWTM', 'Wallmart'))), ('DJC', 'Dow Jones Companies Today'), ('BVC', 'Bitcoin Value Chart')], max_length=8),
        ),
    ]
